### ISSUE TITLE
使用httpclientfactory的时候。如何携带证书呢？

### ISSUE THREAD

**Issue by junlei-lv** [xljiulang/WebApiClient.Extensions#2]
在使用httpclient对象的时候。请求一个接口地址的时候。是可以在请求三种带有证书（某些支付接口场景下要求证书）。
但是在使用httpclientfactory的时候如何携带证书呢？

**Comment by xljiulang** [comment]
HttpClientFactory有ConfigurePrimaryHttpMessageHandler方法，这里可以创建HttpClientHandler，并给Handler添加上证书。

**Comment by junlei-lv** [comment]
ok
感谢，我看看这个方法去

**Comment by junlei-lv** [comment]
抱歉，没找到这个方法 ConfigurePrimaryHttpMessageHandler  啊。

**Comment by xljiulang** [comment]
你用哪个扩展项目？你把代码帖出看看

**Comment by junlei-lv** [comment]
ConfigurePrimaryHttpMessageHandler方法中只能配置唯一的一个HttpClientHandler对象。
但是，实际中对于同一个接口地址，可能会有不同的账号，不同的证书，这里怎么去动态的定义传入的证书呢？就跟动态的入参一样。

**Comment by xljiulang** [comment]
动态传入证书是不可能的了，因为证书是用于SSL连接的，在tcp连接之后就需要SSL握手，也就是说一个http连接，要么是SSL连接，要么是普通TCP连接，不可切换。
